name: CI

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['master']
    tags: [v*]
  # release:
    # types: [published]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: ["2.12.17", "2.13.10"]
    runs-on: ubuntu-latest
  
    env:
      SCALA_VERSION:  ${{ matrix.scala }}
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: coursier/cache-action@v6
      # - uses: olafurpg/setup-scala@v13
        # with:
          # java-version: adopt@1.8

      - name: unzip rasters
        run: cd raster/data; unzip geotiff-test-files.zip

      - name: run tests
        run: docker compose -f .github/docker-compose.yml up test --abort-on-container-exit --exit-code-from test

  publish:
    name: Publish Artifacts
    needs: [build]
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8]
        distribution: [temurin]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: coursier/cache-action@v6
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}

      - name: Release
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SO_PW }}
          SONATYPE_USERNAME: ${{ secrets.SO_UN }}
        if: ${{ env.SONATYPE_PASSWORD != '' && env.SONATYPE_USERNAME != '' }}
